### ISSUE TITLE
[Tarefa - 12] - Deletar anotação

### ISSUE THREAD

**Issue by AntonioAldisio** [fga-eps-mds/2022-2-CAPJu-Service#12]
## Descrição.

Desenvolver endpoint que possa deletar anotação selecionada.

## Critérios de aceitação

- [ ] Endpoint de deletar de anotação

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Service/12?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
