### ISSUE TITLE
[HU - 02]  Gerar notificações

### ISSUE THREAD

**Issue by ilus1** [fga-eps-mds/2022-2-CAPJu-Service#13]
# Descrição

Como Estagiário/Servidor/Diretor,
eu quero receber notificações de atraso de um processo,
para que processos atrasados possam receber a devida atenção.

## Critérios de aceitação

- [ ] Sistema deve gerar notificações sobre processos atrasados.
- [ ] Sistema deve receber no mínimo 1 usuário como recebedor de notificações para cada fluxo
- [ ] Sistema calcula prazo do processo a partir do dia que o processo entrou na etapa.
- [ ] Sistema envia notificações por email.

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Service/13?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7

**Comment by DaviAntonio** [comment]
Fechar devido à migração para fga-eps-mds/2022-2-CAPJu-Doc#132
