### ISSUE TITLE
[Tarefa - 14] Atribuir prazo ao processo

### ISSUE THREAD

**Issue by ilus1** [fga-eps-mds/2022-2-CAPJu-Service#14]
## Descrição.
O  sistema deverá atribuir um prazo ao processo. O prazo se dá a partir da soma do dia atual, derivado do sistema, somado com o prazo da etapa que o processo está.

## Critérios de aceitação

- [ ] Prazo deve ser atribuido automaticamente.
- [ ] Prazo deve ser atualizado quando o processo trocar de etapas.
- [ ] Prazo deverá contar dia atual como um dia completo para a soma do prazo.

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Service/14?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7

**Comment by DaviAntonio** [comment]
Atualizar relacionamento do fga-eps-mds/2022-2-CAPJu-Service#13 para o fga-eps-mds/2022-2-CAPJu-Doc#132

**Comment by DaviAntonio** [comment]
Fechando devido à migração para fga-eps-mds/2022-2-CAPJu-Doc#133
