### ISSUE TITLE
 Remoção de funcionalidades e código duplicados

### ISSUE THREAD

**Issue by vitorAlves7** [fga-eps-mds/2022-2-CAPJu-Service#3]
## Descrição

Remover e refatorar códigos que estão nos dois microsserviços e verificar seu funcionamento 

## Tarefas
- [ ]  Remoção de duplicação de funcionalidades/código 

## Critérios de Aceitação
Código menos repetitivo e mais reaproveitável

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Service/3?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
