### ISSUE TITLE
Reestruturar os endpoints para se adaptar ao novo banco

### ISSUE THREAD

**Issue by vitorAlves7** [fga-eps-mds/2022-2-CAPJu-Service#4]
## Descrição

Modificar o funcionamento de alguns métodos e classes que estão acopladas ao funcionamento do antigo baco

## Tarefas
- [ ] Modificar os endoints para o funcionamento com o novo banco

## Critérios de Aceitação
Remoção dos Schemas e refatoração de alguns métodos acoplados ao mongo

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Service/4?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7

**Comment by DaviAntonio** [comment]
Tarefa migrada para fga-eps-mds/2022-2-CAPJu-Doc#136
