### ISSUE TITLE
[Tarefa - 02] Preparação do Banco de Dados

### ISSUE THREAD

**Issue by DaviAntonio** [fga-eps-mds/2022-2-CAPJu-Service#5]
# [Tarefa - 02] Preparação do Banco de Dados

## Descrição

Atualizar a modelagem do Banco de Dados e implementá-la no projeto

## Tarefas
- [x] Atualizar a modelagem com processo terminado
- [x] Atualizar a modelagem com pertencer a vários fluxos
- [x] Configurar atributo para número do processo padrão CNJ
- [x] Atualizar o modelo com cadastro de usuários da unidade que receberão os e-mails de atraso de processos em etapa
- [ ] Atualizar o modelo com cadastro de dias sem expediente
- [ ] Atualizar o modelo para atribuir as estatísticas aos processos nos fluxos
- [x] Decidir o ORM
- [x] Preparar classes de modelo para o ORM
- [x] Criar esquema no PostgreSQL
  - [x] Criar *migrations* necessárias para criar as tabelas e as restrições
- [ ] Popular banco com um sysadmin
- [x] Preparar imagem docker para o SGBD

### Número do processo 
- [x] Número do processo armazenado em VARCHAR
- [ ] padrão CNJ (NNNNNNN-DD.AAAA.J.TR.OOOO)
  - [ ] 20 dígitos
  - [ ] 6 campos OBRIGATÓRIOS (máscara)
- [ ]  O campo (NNNNNNN), com 7 dígitos, identifica o número sequencial do processo por unidade de origem (OOOO)
- [ ] O campo (DD), com 2 dígitos, identifica o dígito verificador
- [ ]  campo (AAAA), com 4 dígitos, identifica o ano do ajuizamento do processo.
- [ ] O campo (J), com 1 dígito, identifica o órgão ou segmento do Poder Judiciário
- [ ] O campo (TR), com 2 (dois) dígitos, identifica o tribunal do respectivo segmento do Poder Judiciário e, na Justiça Militar da União, a Circunscrição Judiciária
- [ ] O campo (OOOO), com 4 (quatro) dígitos, identifica a unidade de origem do processo

### Imagem docker
- [ ] imagem docker do Postgres deve ser integrada aos microsserviços do projeto

### Código
- [x] ORM integrado à base de dados
- [x] Classes de modelos implementadas
- [ ] População dos dados iniciais
  - [ ] Criação de usuário administrador

### Documentação
- [x] Disponibilizar Modelo Entidade-Relacionamento

## Informação Adicional (se aplicável)

[Padrão CNJ atualizado até 2022-11-29](https://atos.cnj.jus.br/files/compilado23285720221017634de539229ab.pdf)

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Service/5?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7

**Comment by DaviAntonio** [comment]
O ORM escolhido foi o Sequelize

https://sequelize.org/
https://www.youtube.com/watch?v=Fbu7z5dXcRs

**Comment by DaviAntonio** [comment]
Devido a reunião de 2022-12-05, o modelo da base de dados terá que ser refeito:
- incluir cadastro no fluxo de quem receberá os emails de processos atrasados nas etapas
- incluir cadastro dos dias sem expediente
- estatísticas são referentes aos fluxos

**Comment by DaviAntonio** [comment]
Atualizar devido a fga-eps-mds/2022-2-CAPJu-Doc#124

**Comment by DaviAntonio** [comment]
Tarefa migrada para fga-eps-mds/2022-2-CAPJu-Doc#136
