### ISSUE TITLE
Implementar testes

### ISSUE THREAD

**Issue by vitorAlves7** [fga-eps-mds/2022-2-CAPJu-Service#6]
## Descrição
Implementação dos testes 

## Tarefas
- [ ] Testes unitários do service

## Critérios de Aceitação
Aumentar a cobertura de testes atual

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Service/6?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
