### ISSUE TITLE
Criar pipeline de CD

### ISSUE THREAD

**Issue by AntonioAldisio** [fga-eps-mds/2022-2-CAPJu-Service#7]
## Descrição

Desenvolver no github actions uma pipeline de CD (Deploy continuous). 

## Tarefas
- [x] Definir repositorio de armazenamento de imagem (Docker Hub ou Azure)
- [x] Inserir secrets no repositorio
- [x] Definir branch que irá atuar sobre essa pipeline.
- [x] Escolher padrão de tag adotado na publicação da imagem

## Critérios de Aceitação

Imagem publicada em um repositorio de imagens disponivel para baixar por quem tiver permisão

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Service/7?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
